# Generated by Django 5.2.1 on 2025-07-16 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custom_zenith', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_data', models.JSONField(blank=True, default=dict, verbose_name='dados do perfil')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='foto de perfil')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última atualização')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil de usuário',
                'verbose_name_plural': 'perfis de usuários',
            },
        ),
    ]
