# Generated by Django 5.2.1 on 2025-07-18 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custom_zenith', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('color', models.CharField(default='#6d28d9', help_text='Cor em hexadecimal (ex: #6d28d9)', max_length=7, verbose_name='cor')),
            ],
            options={
                'verbose_name': 'categoria de post',
                'verbose_name_plural': 'categorias de posts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DevlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('excerpt', models.TextField(help_text='Breve resumo do post (máximo 300 caracteres)', max_length=300, verbose_name='resumo')),
                ('featured_image', models.ImageField(upload_to='devlog_images/', verbose_name='imagem destacada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última atualização')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devlog_posts', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_custom_zenith.postcategory', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'post do devlog',
                'verbose_name_plural': 'posts do devlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última atualização')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_custom_zenith.devlogpost', verbose_name='post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'comentário',
                'verbose_name_plural': 'comentários',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app_custom_zenith.devlogpost', verbose_name='post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'curtida',
                'verbose_name_plural': 'curtidas',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
