# Generated by Django 5.2.1 on 2025-07-18 20:41

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custom_zenith', '0003_postcategory_devlogpost_postcomment_postlike'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devlogpost',
            options={'ordering': ['-published_at', '-created_at'], 'permissions': [('can_publish_post', 'Pode publicar posts'), ('can_archive_post', 'Pode arquivar posts')], 'verbose_name': 'post do devlog', 'verbose_name_plural': 'posts do devlog'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='devlogpost',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_data',
        ),
        migrations.AddField(
            model_name='devlogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160, verbose_name='meta descrição'),
        ),
        migrations.AddField(
            model_name='devlogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='data de publicação'),
        ),
        migrations.AddField(
            model_name='devlogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=10, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='devlogpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='visualizações'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criação'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Comentários aprovados são visíveis publicamente', verbose_name='aprovado?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='biografia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date_visibility',
            field=models.CharField(choices=[('public', 'Público'), ('friends', 'Apenas amigos'), ('private', 'Privado')], default='private', max_length=10, verbose_name='visibilidade da data de nascimento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='localização'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_nascimento',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1), message='Data de nascimento inválida.')], verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='devlogpost',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='devlog_posts', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='devlogpost',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='app_custom_zenith.postcategory', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='devlogpost',
            name='content',
            field=models.TextField(help_text='Conteúdo principal do post', verbose_name='conteúdo'),
        ),
        migrations.AlterField(
            model_name='devlogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Breve resumo do post (máximo 300 caracteres)', max_length=300, verbose_name='resumo'),
        ),
        migrations.AlterField(
            model_name='devlogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Imagem principal do post (recomendado 1200x630 pixels)', null=True, upload_to='devlog_images/%Y/%m/', verbose_name='imagem destacada'),
        ),
        migrations.AlterField(
            model_name='devlogpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='URL amigável para o post (gerado automaticamente se vazio)', max_length=220, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='devlogpost',
            name='title',
            field=models.CharField(help_text='Título do post (máximo 200 caracteres)', max_length=200, unique=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(max_length=60, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Imagem de perfil do usuário', null=True, upload_to='profile_images/%Y/%m/', verbose_name='foto de perfil'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='app_custom__email_737bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='app_custom__usernam_65bddc_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['telefone'], name='app_custom__telefon_c09a96_idx'),
        ),
        migrations.AddIndex(
            model_name='devlogpost',
            index=models.Index(fields=['slug'], name='app_custom__slug_5f50c4_idx'),
        ),
        migrations.AddIndex(
            model_name='devlogpost',
            index=models.Index(fields=['status'], name='app_custom__status_06a2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='devlogpost',
            index=models.Index(fields=['created_at'], name='app_custom__created_925dda_idx'),
        ),
        migrations.AddIndex(
            model_name='devlogpost',
            index=models.Index(fields=['published_at'], name='app_custom__publish_6e7318_idx'),
        ),
    ]
