# Generated by Django 5.2.1 on 2025-07-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_custom_zenith', '0004_alter_devlogpost_options_alter_customuser_managers_and_more'),
    ]

    operations = [
    ]
