# Generated by Django 5.2.1 on 2025-07-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custom_zenith', '0005_auto_20250718_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de criação'),
        ),
    ]
