# Generated by Django 5.2.1 on 2025-07-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custom_zenith', '0006_alter_postcategory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cargo/função'),
        ),
    ]
