# Generated by Django 5.2.1 on 2025-07-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custom_zenith', '0007_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data_entrada',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='data de entrada'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter'),
        ),
    ]
