# Generated by Django 4.2 on 2026-01-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custom_zenith', '0008_userprofile_data_entrada_userprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Prefere usar o modo escuro?', verbose_name='modo escuro'),
        ),
    ]
