# Generated by Django 4.2 on 2026-01-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custom_zenith', '0009_userprofile_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug'),
        ),
    ]
