# Generated by Django 4.2 on 2026-01-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custom_zenith', '0010_alter_postcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de création'),
        ),
    ]
